### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by kurthalex** [ethereum/viper#265]
I have a error when I run `python setup.py test`
I have the same error when I go the test folder and I execute `python test_parser.py`

A have archlinux with python 3.6.0 and viper has been installed in a fresh virtualenv with `python setup.py install `

`Traceback (most recent call last):
  File "test_parser.py", line 16, in <module>
    state_transition.apply_transaction(s.state, rlp.decode(u.decode_hex('f903bd808506fc23ac008304c1908080b903aa6103988061000e6000396103a65660006101bf5361202059905901600090526101008152602081019050602052600060605261040036018060200159905901600090528181526020810190509050608052600060e0527f0100000000000000000000000000000000000000000000000000000000000000600035046101005260c061010051121561007e57fe5b60f86101005112156100a95760c061010051036001013614151561009e57fe5b6001610120526100ec565b60f761010051036020036101000a600161012051013504610140526101405160f7610100510360010101361415156100dd57fe5b60f76101005103600101610120525b5b366101205112156102ec577f01000000000000000000000000000000000000000000000000000000000000006101205135046101005260e0516060516020026020510152600160605101606052608061010051121561017a57600160e0516080510152600161012051602060e0516080510101376001610120510161012052602160e0510160e0526102da565b60b8610100511215610218576080610100510360e05160805101526080610100510360016101205101602060e05160805101013760816101005114156101ef5760807f010000000000000000000000000000000000000000000000000000000000000060016101205101350412156101ee57fe5b5b600160806101005103016101205101610120526020608061010051030160e0510160e0526102d9565b60c06101005112156102d65760b761010051036020036101000a6001610120510135046101405260007f0100000000000000000000000000000000000000000000000000000000000000600161012051013504141561027357fe5b603861014051121561028157fe5b6101405160e05160805101526101405160b761010051600161012051010103602060e05160805101013761014051600160b7610100510301016101205101610120526020610140510160e0510160e0526102d8565bfe5b5b5b602060605113156102e757fe5b6100ed565b60e051606051602002602051015261082059905901600090526108008152602081019050610160526000610120525b6060516101205113151561035c576020602060605102610120516020026020510151010161012051602002610160510152600161012051016101205261031b565b60e0518060206020606051026101605101018260805160006004600a8705601201f161038457fe5b50602060e051602060605102010161016051f35b6000f31b2d4f'), transactions.Transaction))
  File "/home/alex/.virtualenvs/viper/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/ethereum/state_transition.py", line 211, in apply_transaction
    validate_transaction(state, tx)
  File "/home/alex/.virtualenvs/viper/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/ethereum/state_transition.py", line 159, in validate_transaction
    if not tx.sender:  # sender is set and validated on Transaction initialization
  File "/home/alex/.virtualenvs/viper/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/ethereum/transactions.py", line 89, in sender
    pub = ecrecover_to_pub(rawhash, v, self.r, self.s)
  File "/home/alex/.virtualenvs/viper/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/ethereum/utils.py", line 79, in ecrecover_to_pub
    assert pow(xc, (SECP256K1P - 1) / 2, SECP256K1P) == 1
TypeError: pow() 3rd argument not allowed unless all arguments are integers`

**Comment by fubuloubu** [comment]
@kurthalex This should now be settled with updates to installation and testing setup.

Can we close?

**Comment by DavidKnott** [comment]
@fubuloubu @kurthalex This seems like an outdated issue, closing it now.
