### ISSUE TITLE
Error: Cannot send value to non-payable function

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/viper#270]
Testing a simple deposit contract and getting a couple of issues.  I'll point the one out here and start a new ticket for the other problem.

    Error: Cannot send value to non-payable function
        at web3.js:4057:19
        at <anonymous>:1:1

How to reproduce: 

# Contract

    owner: address
    depositors: wei_value[address]
    depositorsNext: num

    def __init__(_owner: address):
        self.owner = _owner
        self.depositorsNext = 1

    def check_balance() -> wei_value:
        # Return our current balance 
        return(self.balance)

    def drain():
        # Send all stored value to owner
        send(self.owner, self.balance)

    def deposit() -> bool:
        # Deposit value in the contract and record the sender and value 
        
        assert(msg.value > 0)

        if self.depositors[msg.sender]:
            self.depositors[msg.sender] += msg.value
            return True
        else:
            self.depositors[msg.sender] = msg.value
            return True

# Deploy with geth

    > var abi = [ { "inputs":[ {"name": "beneficiary", "type": "address"}, ], "type": "constructor" }, { "type": "function", "name": "check_balance", "constant": true, "inputs": [], "outputs": [{"name": "balance", "type": "uint"}] }, { "type": "function", "name": "drain", "constant": false, "inputs": [], "outputs": [] }, { "type": "function", "name": "deposit", "constant": false, "inputs": [], "outputs": [{"name": "success", "type": "bool"}] }]
    > var bcode = "0x600035601c52740100000000000000000000000000000000000000006020526fffffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff000000000000000000000000000000016060527402540be3fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffdabf41c00000000000000000000000002540be40060a05260206020380360c03960c05160205181101558575060206020380360c03960c05160005560016002556101f456600035601c52740100000000000000000000000000000000000000006020526fffffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff000000000000000000000000000000016060527402540be3fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffdabf41c00000000000000000000000002540be40060a0526398ba1d4660005114156100ad57303160005260206000f3005b639890220b60005114156100ce57600060006000600030316000546000f150005b63d0e30db06000511415610132576000341315585733600160c05260c06020200154156101175733600160c05260c06020200134815401815550600160005260206000f3610130565b3433600160c05260c06020200155600160005260206000f35b005b5b6100c16101f4036100c16000396100c16101f4036000f3"
    > ct = eth.contract(abi)
    > ct.new("0xea4aca379b0c21b36e51380e5de936b61ca63176", , {from: eth.accounts[0], data: bcode, gas: 4000000})

# Deposit

    > x = ct.at("0xdeadbeef...")
    > x.deposit.sendTransaction({from: eth.accounts[1], value: web3.toWei(1, "ether")})
    Error: Cannot send value to non-payable function
        at web3.js:4057:19
        at <anonymous>:1:1

Perhaps I'm missing something on how to send value to a function?

**Comment by vbuterin** [comment]
Try now. I added a payable modifier to the language and the ABI, though any function that you want to send ether to will need an @payable decorator.

**Comment by mikeshultz** [comment]
Using the `@payable` decorator on the `deposit` function on the test contract in this thread still results in the same error as before.  Using the latest from the `master` branch, though the `viper` executable still shows version `0.0.1`.  Double checked, and the new version of viper is putting out different bytecode, so I'm sure I'm not just running the old version.

I tried removing the return value from the `deposit` function as well, no dice.  Let me know if there's more information I can provide.

**Comment by fubuloubu** [comment]
@mikeshultz Adding `@payable` decorator to `deposit()` works in the latest. Any further issues with your example?

**Comment by mikeshultz** [comment]
@fubuloubu You tested the example with `@payable` and it worked?  My tests failed, but I can try again if you've seen it work.  Maybe I missed something on my latest test.

**Comment by fubuloubu** [comment]
Yeah, just add the decorator above the function definition

**Comment by DavidKnott** [comment]
@mikeshultz Is the `@payable` decorator working for you now?

**Comment by mikeshultz** [comment]
Yes, sorry about that, I screwed up my ABI.  This does indeed work now.
