### ISSUE TITLE
Very high gas on function

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/viper#271]
Same test contract as #270.

    owner: address
    depositors: wei_value[address]
    depositorsNext: num

    def __init__(_owner: address):
        self.owner = _owner
        self.depositorsNext = 1

    def check_balance() -> wei_value:
        # Return our current balance 
        return(self.balance)

    def drain():
        # Send all stored value to owner
        send(self.owner, self.balance)

    def deposit() -> bool:
        # Deposit value in the contract and record the sender and value 
        
        assert(msg.value > 0)

        if self.depositors[msg.sender]:
            self.depositors[msg.sender] += msg.value
            return True
        else:
            self.depositors[msg.sender] = msg.value
            return True

When using `geth` to estimate gas on the `deposit` function, I'm getting gas higher than the block limit.  Is this a `viper` compiler error, or just a really poorly defined function on my part?

    > test_contract.deposit.estimateGas()
    4712388

**Comment by vbuterin** [comment]
Maybe geth's gas estimator has no idea how to handle Viper's way of doing conditional throws (PC JUMPI) ?

**Comment by DavidKnott** [comment]
@mikeshultz Is this still happening?  If it is I'll look into it.

**Comment by DavidKnott** [comment]
@mikeshultz I'm closing this issue, if it's still a problem please create another issue
