### ISSUE TITLE
Can't get past secp256k1 no find on pkg-config

### ISSUE THREAD

**Issue by greggdourgarian** [ethereum/viper#272]
Seems to be a common problem w secp256k1 installs.   Anyone else get past it?

Would be nice to have a docker container for this environment.  Anyone have one?

**Comment by fubuloubu** [comment]
I had luck with `pip install secp256k1`. Might be a missing dependancy in the setup.py. Also solved some error with libffi missing header.

**Comment by fubuloubu** [comment]
Also note this project uses python 3.6, which I had trouble running the installation for until I installed these packages `#sudo apt install build-essential automake pkg-config libtool libffi-dev libgmp-dev`.
Then `SECP_BUNDLED_EXPERIMENTAL=1 pip install secp256k1` works, and THEN you can install using `python setup.py install`

**Comment by fubuloubu** [comment]
@greggdourgarian Not having issues anymore with this. Can we close?

**Comment by DavidKnott** [comment]
@fubuloubu This seems like an outdated issue, closing it now.  @greggdourgarian If you're still having  problems we can reopen it and I'll look into secp256k1 installation.
