### ISSUE TITLE
Testing framework can't handle function calls?

### ISSUE THREAD

**Issue by pdaian** [ethereum/viper#274]
I have the following Viper contract:
```
def b() -> bool:
    return true

def a() -> bool:
    return self.b()
```

I am trying to test it as follows:
```
from ethereum import tester as t
s = t.state()
from viper import compiler
t.languages['viper'] = compiler.Compiler() 

c = s.abi_contract(open('examples/test.vy').read(), language='viper')

print(c.b())
print(c.a())
```

The tester gives me an error as follows:
```
Traceback (most recent call last):
  File "test_test.py", line 9, in <module>
    print(c.a())
  File "/usr/local/lib/python3.6/dist-packages/ethereum/tester.py", line 143, in kall
    **dict_without(kwargs, 'sender', 'value', 'output')
  File "/usr/local/lib/python3.6/dist-packages/ethereum/tester.py", line 312, in _send
    raise TransactionFailed()
ethereum.tester.TransactionFailed
```

Which from reading the tester code looks like an out of gas error?

is this intended behavior / how best to proceed with testing contracts which call their own functions?

it's worth noting that when I compile and deploy the EVM generated:
```
$ viper examples/test.vy 
0x61011256600035601c52740100000000000000000000000000000000000000006020526fffffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff000000000000000000000000000000016060527402540be3fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffdabf41c00000000000000000000000002540be40060a05263f8a8fd6d60005114156100bc576ffffffffffffffffffffffffffffffffe60005260206000f3005b634df7e3d060005114156100d657600160005260206000f3005b630dbe671f600051141561010d5760206101a06004634df7e3d06101405261015c6000305af11558576101a05160005260206000f3005b5b61000461011203610004600039610004610112036000f3
```

in Geth's development mode, the dispatch works fine.

**Comment by vbuterin** [comment]
> from ethereum import tester as t

This is an outdated version of pyethereum. You want to download the latest develop branch, in which case it would change to `from ethereum.tools import tester as t` (along with a few other API changes). Everything works fine in the latest version:

    >>> from ethereum.tools import tester as t
    >>> x = t.Chain()
    Initializing chain from provided state
    >>> c = x.contract(open('/tmp/1').read(), language='viper')
    >>> print(c.a())
    True
    >>> print(c.b())
    True
