### ISSUE TITLE
`make` fails with missing requirements.txt

### ISSUE THREAD

**Issue by pirapira** [ethereum/viper#276]
On revision e840cef195d71b317cec425bf8ec30c6cfa3be33, I see

```
$ make
pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by fubuloubu** [comment]
I just noticed this too. The Makefile is superseded by setup.py and should be deleted.

**Comment by DavidKnott** [comment]
@pirapira @fubuloubu Instead of deleting the makefile how does me making a PR to change the makefile to this sound?
```
init:
    python setup.py install
```

**Comment by fubuloubu** [comment]
Sure, that works too as the `test` rule still works

**Comment by DavidKnott** [comment]
@pirapira @fubuloubu I believe this issue has been dealt with, closing it now.
