### ISSUE TITLE
Add code coverage framework

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#283]
From #282 
Add method (or makefile rule) to obtain coverage metrics for current tests

**Comment by fubuloubu** [comment]
I have a commit that upgrades all the tests (357 total) to py.test, 100% passing with no warnings/errors and 87% coverage using pytest-cov. Here's the coverage metrics:
```
----------- coverage: platform linux, python 3.6.1-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
viper/__init__.py           2      0   100%
viper/compile_lll.py      217     20    91%
viper/compiler.py          29      2    93%
viper/exceptions.py        33      7    79%
viper/functions.py        341     23    93%
viper/opcodes.py            7      0   100%
viper/optimizer.py         82     18    78%
viper/parser.py           825     93    89%
viper/parser_utils.py     217     53    76%
viper/types.py            254     52    80%
viper/utils.py             42      4    90%
-------------------------------------------
TOTAL                    2049    272    87%
```
I'm having problems with setup.py getting the right packages, will debug tomorrow.

**Comment by fubuloubu** [comment]
Fixed those issues, pull request #284

**Comment by beaugunderson** [comment]
if #284 gets merged I'm happy to build on it by integrating codecov.io as well (free for opensource repos); the primary benefits are:

- being able to see code coverage visually per file via their interface and while browsing github (via an extension)
- code coverage increase/decrease stats on every pull request, and ability to require that PRs not decrease coverage if desired

**Comment by fubuloubu** [comment]
#284 merged, this issue is closed.

@beaugunderson if you want to open a separate issue for integrating a code coverage monitor, good idea. Not sure if requiring no decrease in coverage for a PR is a good idea for a project this young however.
