### ISSUE TITLE
How to search a variable-sized array

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#288]
@vbuterin I am writing a viper example contract for owning shares in a company. Since anyone can buy, the array of shareholders grows with each buy order from a new account. For discussion purposes, the signature of my array is `stockholders: {account: address, stock: num}[num]` and `num_stockholders` is initialized to zero in my contract creation.

I tried: 
```
for i in range(self.num_stockholders):
  if msg.sender == stockholders[i].account:
    self.stockholders[i].stock += buy_order
```
which doesn't work because the compiler expects a non-zero, positive size for "number of rounds" in range. I can't reason my way out of this even given your crowdfunding example. The len can be zero, so does that mean this isn't possible to compile (search a variable-sized array)? How does my function get called again if my length exceeds the static number I'm using for "rounds" (30 in your example to avoid gas limit issues). Would appreciate any help you can provide.

Additionally, I think an easier, language-implemented way to obtain a member of or set a value in an array like this would be awesome. Something like `if msg.sender in stockholders::account` (e.g. list of values for one key in dict list) and `stockholders[account==msg.sender].stock += msg.value / price` (e.g. incr value for given key for matching item in list) would make it a lot easier to write more concise, readable code for a contract. I'm no programming language expert (especially not with EVM), but some means to represent these very common patterns would be super helpful and potentially optimizable in the bytecode I would think. I would like to write something like:
```
# If sender is on the books, increment their shares
if msg.sender in stockholders::account:
  self.stockholders[account==msg.sender].stock += msg.value / price
else:
  # Add sender to the books with the amount of shares purchased
  self.num_stockholders += 1
  self.stockholders[self.num_stockholders] = {account: msg.sender, stock: msg.value / price}
```

**Comment by vbuterin** [comment]
I think what you want is something like:

```
stockholders: address[num]
num_stockholders: num
stockholder_reverse_lookup: num[address]

def add_to_shareholder_list():
    assert <msg.sender is eligible>
    self.stockholders[self.num_stockholders] = msg.sender
    self.stockholder_reverse_lookup[msg.sender] = self.num_stockholders + 1
    self.num_stockholders += 1

def lookup(addr: address) -> num:
    return self.stockholder_reverse_lookup[addr] - 1
```

**Comment by fubuloubu** [comment]
I was looking at #270 and realized that these extra bookkeeping parameters weren't necessary, as I was trying to make an account -> value lookup, which would look something like this:
```
stockholders: {stock: num}[address]

def some_function(_stock: num):
    # Check for existance
    if self.stockholders[msg.sender]:
        # Add value
        self.stockholders[msg.sender].stock += _stock
    else:
        # Add new item to lookup (basically a dict of account: { properties } items)
        self.stockholders[msg.sender] = {stock: _stock}
```
and for my case, that obviously reduces to:
```
stockholders: num[address]
def some_function(stock: num):
    if self.stockholders[msg.sender]:
        self.stockholders[msg.sender] += stock
    else:
        self.stockholders[msg.sender] = stock
```

Just wanted to note that there was a way better way of managing this kind of lookup than what was suggested, and that if multi-property lookups are desired, there was a nice method to do that.
