### ISSUE TITLE
Semantic Version in Viper

### ISSUE THREAD

**Issue by yograterol** [ethereum/viper#294]
@vbuterin do you like to implement http://semver.org/ to Viper?

The idea is:

1- Manage the Viper's version according to the backwards-compatible features/fixes.
2- Freeze the dependencies version with every Viper's version.
3- To have a CHANGELOG in the repo.

**Comment by fubuloubu** [comment]
I was thinking about this today, apparently `pyethereum` uses `bumpversion` to handle version updates. Created PR #312 to integrate that library, although the first tag still needs to get created for it to be fully integrated.

That should address item 1 from your list. A user still has to manually use `bumpversion` to update the version, but at least it's one command and the package maintainer has experience with the tool.

Item 2 I believe is not a concern given our choice of setuputils to manage the dependancies?

Item 3 is not addressed, at least as far as I know. Maybe bumpversion has some extension or feature to create change logs, but this is also probably not necessary until an alpha is released.

Thoughts?

**Comment by yograterol** [comment]
@fubuloubu great! 

It's ok to use `bumpversion`, go for it.

About Item 2, my point is keeping the right dependencies version with each new viper version.

Item 3, if we start now with a CHANGELOG or we automate the process from a early stage is better, no? IMHO.

Good job with the PR.

**Comment by fubuloubu** [comment]
Sure. I have no experience maintaining a changelog, or whether tools exist for managing that automatically via examining git logs, checking API changes, etc. Figuring that out now would be cool, but I think integrating after at least the first alpha or beta release might be a better time for it.

If you know more about managing changelogs automatically, be my guest!

**Comment by DavidKnott** [comment]
@yograterol @fubuloubu This issue seems taken care of by PR  #312 can it be closed?

**Comment by yograterol** [comment]
@DavidKnott yes
