### ISSUE TITLE
Array of bytes has infinite type size

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#303]
I am pretty sure this is an error, although I am a bit unclear behind the purpose of declaring the size of a type to be infinite. Is this a part of the gas estimate?

Anyways, if you define an array of bytes using another type, it throws an error e.g.:
```python
def __init__(test: bytes32[bool]):
    pass
```

even though that data size should only be 64 bytes max (32 bytes x 2 possible values for bool)

Would appreciate some understanding behind the purpose of this check and if there is supposed to be a deeper check occuring, like some sort of maximum (or reasonable) number of bytes we should be allowed to use? (distinct from their economic cost to store them)

**Comment by fubuloubu** [comment]
I think the problem with my example is only in function arguments... hmm

**Comment by vbuterin** [comment]
Viper assumes maps all have infinite type size; you're right that it's incorrect in that particular case. IMO it's not worth it to have some kind of special-case support for two-item maps.

**Comment by fubuloubu** [comment]
I agree with you on that, it was a spurious example.

More for my understanding, what is the reasoning behind this decision? A viper contract can store it's own data in maps, which could reach infinite size in theory, but function arguments (or return values) are not allowed to be of variable size. Is this to ensure that gas estimates can be computed, or something more fundamental to the EVM?

I'm still very much learning, excuse my ignorance!

**Comment by vbuterin** [comment]
The reason why infinite sized types in general are not allowed as function arguments is indeed gas estimation. The reason why maps specifically are not allowed is that there is no standard for how an entire map can be passed around as a data structure in the ABI, and the code complexity of implementing such a format, as well as the mechanisms for converting between this format and storage maps, is hard.

**Comment by fubuloubu** [comment]
@vbuterin as a suggestion, can we change that error message to "Maps are not supported for function arguments or outputs"? A much more descriptive error than "has infinite size"

**Comment by yograterol** [comment]
@fubuloubu that's great idea.

**Comment by fubuloubu** [comment]
Thanks @yograterol. I'll close this one
