### ISSUE TITLE
Get complete listing of gas estimates for contract

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#306]
Some way to get a gas estimate for each function in a contract would be sweet, allowing you to profile the gas-intensive functions you might have but are unaware of and also see it in client programs/editors.

@vbuterin Can this be included in the ABI output? Does that make sense? I am not familiar with the requirements or uses of that format enough

**Comment by vbuterin** [comment]
Yeah, I think it would be sensible to add the gas estimate into the ABI, alongside the other fields.

**Comment by fubuloubu** [comment]
Easier than I thought, #308

Feel free to change the string used to store it in the ABI if you so choose.
