### ISSUE TITLE
Failed `send` doesn't error or return false

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/viper#310]
Right now when I run:
```
send(msg.sender, self.balance + 1)
```
It neither errors nor returns false.  I would like to implement functionality similar to Solidity where a failed `send` returns false and implement `transfer`  which will throw on failure.  Thoughts?

**Comment by fubuloubu** [comment]
I'd say that's a major issue. Does the balance remain what it was, or is everything lost?

**Comment by DavidKnott** [comment]
The balance remains which is good, I'm making a PR so that send returns a `bool`.

**Comment by fubuloubu** [comment]
I think someone was discussing `send()` and how it should throw an exception instead of return `True / False`. I'm not sure of the subtlties, but I would prefer any transaction that is supposed to send me money to fail if the transaction doesn't work.

**Comment by DavidKnott** [comment]
I agree, that people should have that functionality but I like the idea of doing it like Solidity does by having `send`  which returns a `bool` and `transfer` which throws so that people can choose.
