### ISSUE TITLE
QUESTION: Inline assembly

### ISSUE THREAD

**Issue by Dexaran** [ethereum/viper#316]
Is there any possibility of inline assembly in Viper?

The inline assembly is often used in Solidity, because the functionality of the language does not allow developers to implement many things without it.

**Comment by fubuloubu** [comment]
I believe this would not be something the language aims for, as it is trying to be simple to understand and to use and inline assembly is definitely not that. What sort of EVM assembly code do you typically use, how do you use it, and can we add features to replicate those common usages of assembly in native viper code?

**Comment by Dexaran** [comment]
The most common example is assembling code at the given address to decide whether the given address is a contract or not.

**Comment by Dexaran** [comment]
The another example is the solidity strings library. It is full of assemblies.
https://github.com/Arachnid/solidity-stringutils/blob/master/strings.sol

**Comment by Dexaran** [comment]
I understand that inline assembly is a dangerous feature but I also think that lack of this feature with seriously limit advantages of Viper over solidity.

**Comment by fubuloubu** [comment]
Strings and contract referencing/inheritance are definitely proposed features for Viper. I don't think it is planned to have those features written in Viper, so I think those particular examples would be implemented in the compiler as language constructs

**Comment by Dexaran** [comment]
These are the most important features that I thought about. In any case, I think that having the possibility of inline assembly can help in situations where native language constructs are not enough.
Do you think that Viper functionality will natively cover all aspects that requires assembly in Solidity?

**Comment by fubuloubu** [comment]
In general, I think the goal is to make Viper as easy to use as possible, and therefore harder to create buggy contracts that lose money. I think identifying the usages of assembly in Solidity and implementing features that cover said functionality in Viper have real merit. If you want to take a stab at identifying those features, that would be really great! As someone who has some experience programming embedded devices, I know the power of being able to use assembly to create fast, tight code but it is totally opening pandora's box and is very hard to test which leads to incomprehensible bugs which can lose people a lot of money!

I am not a core dev however, and this project is still in the early stages of development, so I cannot speak absolutely about this feature being in or not in Viper or whether other developers believe in this more conservative design philosophy.

**Comment by vbuterin** [comment]
Personally I would prefer not to have inline assembly. The intent of viper is specifically to make it as difficult as possible to create misleading code, and inline assembly thwarts that. For example, I believe you should be able to Ctrl+F for a variable to see all places in the code where that variable is read or modified; inline assembly would allow a backdoor into variables with mload or sload, and so it would make that impossible.

Viper is not meant to be a language for every use case.

**Comment by fubuloubu** [comment]
@Dexaran again, if you come across any other common uses of assembly in Solidity, it would be great to propose those as Viper features. I would suggest closing this issue however as a no.

@vbuterin Are strings a proposed feature? Maybe stored as an array of 8-bits (or 32 if unicode is eventually to be supported).
I know there is some discussion on contract referencing/inheritance, so I consider that feature in-work. Is that correct?

**Comment by Dexaran** [comment]
@fubuloubu Is your suggestion to implement all use cases of solidity inline assembly as native features in Viper?

**Comment by fubuloubu** [comment]
Yes, but within reason of course. This is not the language for implementing any possible type of concept, but for easy implementation of most common contracts in clear, concise code. I think you have provided two great examples from Solidity that we should try to add to Viper as feature sets (strings and contract referencing), but if you have something very specific and uncommon, Solidity is always an option or just code in EVM assembly directly lol.

**Comment by Dexaran** [comment]
To be honest I don't like solidity... It's very hard-to-read and hard-to-verify when you're auditing a complex system of smart-contracts written in solidity.
I would be happy if Viper will replace it at all.

As for the inline assembly, I will look for more important examples of its use in solidity. I'll provide a full list here.

Most important use cases of inline assembly in solidity:

- Operating with strings.

- Checking if the given address is a contract or not.

**Comment by vbuterin** [comment]
Viper already contains support for strings, or at least byte strings.

Look through the tests starting at [line 929](https://github.com/ethereum/viper/blob/master/tests/test_parser.py#L929) and going down to around line 1378.

**Comment by fubuloubu** [comment]
I acknowledge the capacity for using strings, but my point is more that operations on strings doesn't really exist, and that there could be a string type implemented (with a static size on initialization, and maybe some reasonable default) that contains these operations so that simple things are easy like string concatenation, find/replace, and upper/lower etc. and still maintain the static size invariant (and throws when that invariant is exceeded). Thinking from a database perspective, that stuff is of some importance.

It's more of a extended feature though since most use cases seem to be tracking and exchanging values and simple storing strings. Just would be nice not to have to write an extra 'b' I front of every string lol

**Comment by fubuloubu** [comment]
Also, I think an `iscontract()` function primative would be nice, and more concretely a contract type (extended from address) that asserts the address is a contract

**Comment by vbuterin** [comment]
String concatenation is already available; it's just `new_str = concat(a, b, c...)`

If desired we can certainly add more builtin functions; though I'd prefer to have that be curated by us rather than letting anyone create arbitrary libraries; way too many opportunities for misleading or buggy code that way.

**Comment by vbuterin** [comment]
Will consider a contract type. Something like it would have to happen when we implement ABI calling.

**Comment by DavidKnott** [comment]
Closing this issue due to the added Principles and Goals in the readme.  It feels like inline assembly is not in line with the goals of Viper.
