### ISSUE TITLE
Page not exist for virtualenv guide.

### ISSUE THREAD

**Issue by ponarunkumar** [ethereum/viper#319]
Under Installation section of the documentation,
![image](https://user-images.githubusercontent.com/6130502/29330350-e8498224-81c6-11e7-8423-58f6ff925072.png)

**Broken Link: Page does not exist for virtualenv guide.**
Please review the hyperlink on the installation documentation and share the target url or update respectively. [http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/] Thanks!

**Comment by yograterol** [comment]
This the right URL https://virtualenv.pypa.io/en/stable/

**Comment by ponarunkumar** [comment]
Thanks @yograterol
