### ISSUE TITLE
Errors on Installation

### ISSUE THREAD

**Issue by jenerestain** [ethereum/viper#321]
Tried a fresh install of Viper
Getting an error at line 5

`unicodedecodeerror: 'ascii' codec can't decode byte 0xe8 in position 5559: ordinal not in range(128)`

I fixed this temporarily by just commenting out the readme

Now I'm getting
`src/scrypt.c:27:20: fatal error: Python.h: No such file or directory`

**Comment by yograterol** [comment]
What OS do you have?

`Python.h: No such file or directory`This error is caused because you do not have the Python development libraries installed.

If you have Ubuntu you could install `python3-dev`

**Comment by jenerestain** [comment]
I do have ```python3-dev``` installed

**Comment by DavidKnott** [comment]
@jenerestain Just covering all the bases.
What version of python are you using?
What virtual environment are you using?
What's the output when you run `pip freeze`?

**Comment by DavidKnott** [comment]
@jenerestain I'm closing this issue, if you're still having trouble please open another one and I'll try my best to help you.
