### ISSUE TITLE
Link for python3 for MacOS guide installation returns 404

### ISSUE THREAD

**Issue by avadhootkulkarni** [ethereum/viper#322]
Readme -> Installation -> MacOS -> Point 2: Make sure your python is 3.6 or higher. If not, you could checkout python3 for MacOS guide

Link for python3 for MacOS guide return 404.

The link should be: http://python-guide.readthedocs.io/en/latest/starting/install3/osx/ ?

**Comment by yograterol** [comment]
@avadhootkulkarni you're right

**Comment by DavidKnott** [comment]
The url has been corrected, I'm closing this issue.
