### ISSUE TITLE
Roadmap for Viper?

### ISSUE THREAD

**Issue by yograterol** [ethereum/viper#327]
I saw that 17 days ago Viper doesn't have updates.

How can we help you, @vbuterin? 

If we can create a roadmap, it could be awesome for the project and contributors.

**Comment by DavidKnott** [comment]
I'm about to get started working on Viper full-time so that should speed up development.

**Comment by yograterol** [comment]
@DavidKnott good to know

**Comment by fubuloubu** [comment]
Nice! I know we had a thread of conversation like 3 weeks ago discussing what steps we need to go through, perhaps that can get refined/codified?

**Comment by fubuloubu** [comment]
#279 was that issue

**Comment by yograterol** [comment]
@fubuloubu I agree, it's great to know that @DavidKnott will be contributor full time for Viper, it could push more the Viper's development, @DavidKnott has my support.

I close this issue in favor of #279
