### ISSUE TITLE
Link to the Viper Gitter in the Readme

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/viper#332]
### What's your issue about?
I'd like to have more discussion in the Viper Gitter channel

### How can it be fixed?
Add a link to the Viper Gitter in the Viper readme (towards the top) with a few sentences encouraging discussion and questions.

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/17552858/30087873-575758ea-9260-11e7-9ab7-2ca9373ecd37.png)

**Comment by yograterol** [comment]
Will be great if the contributor doc accompanies it.

**Comment by fubuloubu** [comment]
Well, I didn't even know that was a thing until 30 seconds ago... lol.

**Comment by fubuloubu** [comment]
Further thoughts: Does the grammer, types/feature explanations, and example need to be on the readme? I feel like it's cluttering up that main page and should be moved to the docs (how is that coming by the way? I have no idea what the web address is for the docs).

Also, the example is inconsistent with the one in the `examples/` folder (extra `assert` statement on the README example)

**Comment by DavidKnott** [comment]
I agree 100%, I'll make an issue for it.

**Comment by fubuloubu** [comment]
If you let me know where the documentation is going I can do that for you. I don't understand where that whole skeleton thing is supposed to get generated to work on it though (e.g. web address).

**Comment by DavidKnott** [comment]
That'd be great, here's a link to the Viper [docs](http://eth-viper.readthedocs.io/en/latest/) (currently the build is failing and I haven't to look into it yet).  `make docs` is working though so if you want, you can start moving stuff from the `readme` into the rst files.  I've been using the solidity [docs](https://github.com/ethereum/solidity/tree/develop/docs) as a reference.

**Comment by fubuloubu** [comment]
Oh, okay I gotcha now. I'll check it out tomorrow and submit a PR (or multiple) when I get a chance. It's been driving me a little crazy how scattered everything is when I look for it.

Should we close this issue for now? #333 is merged and closed.

**Comment by DavidKnott** [comment]
That'd be great, I'll close this issue and merge in #333 to keep things clean.
