### ISSUE TITLE
Remove inputs from abi name field.

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/viper#344]
### What's your issue about?
Viper's abi `name` field should not have a functions inputs attached to it for two reasons:
1) Duplicate information (the inputs are already in that abi elsewhere)
2) Abi uniformity, now the `name` field will match Solidity's

### How can it be fixed?

Change abi `name` to not have inputs

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/17552858/30252057-f79e4644-9628-11e7-8cb9-b690f6d19034.png)

**Comment by fubuloubu** [comment]
I found it, submitting a PR with a few other minor tweaks to the ABI for review (added `sig` field to match, might make #335 easier)
