### ISSUE TITLE
Event Type Declaration / Logging

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/viper#346]
### What's your issue about?
This issue is a continuation of #297 (Please see it for context)

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/17552858/30276744-09d05024-96c3-11e7-9347-961951d2966e.png)

**Comment by DavidKnott** [comment]
@fubuloubu Here's the format I'm currently implementing for event logging.

     MyLog: __log__({arg1: num, arg2: indexed(address)})

    def example():
	    MyLog(1, "1d805bC00b8fa3c96aE6C8FA97B2FD24B19a9801")

**Comment by fubuloubu** [comment]
Does the inside of the log need to be a structure?

**Comment by DavidKnott** [comment]
I'd prefer it not being a structure but this :

      MyLog: __log__(arg1: num, arg2: indexed(address))
Isn't valid `python3.6` syntax.

**Comment by fubuloubu** [comment]
Hmm, I guess that makes sense. It's norither a function call not a structure, so it wouldn't parse

Two questions:
1. Is `__log__` a Python object/function?
2. Does `MyLog` name get represented in the output Bytecode (for searching purposes), or is it more of a type declaration e.g. this log call matches these types?

**Comment by DavidKnott** [comment]
1.  No, `__log__` is just a clear way to differentiate events from globals in contracts.
2.  `MyLog` is for type declaration (to be called later) though it will be used for searching in that it will be included in the keccak which will be used to create the `event_id` in the `topics` (topics are the part of an event that can be searched for).

**Comment by fubuloubu** [comment]
Can it be a type then? e.g. `MyLog: log({arg1: num, arg2: indexed(address)})

Actually, I'm using it more like `public`. Could it work like `public`? (And create the right `logger` function)

Further, if set as a type like that, you could set individual entries e.g. `self.MyLog.arg1 = foo` and `self.MyLog.arg2 = bar` and have it commit after all entries are set in a given contract method?

Random thoughts...

**Comment by DavidKnott** [comment]
`MyLog: log({arg1: num, arg2: indexed(address)})` works, though I think using `log` instead of `__log__` could make it harder to read as `__log__` is more obvious.

We could make it so that individual entries can be set, though I don't think we should because then someone reading the code will have to do more work to figure out what's being logged.

I think both your ideas would improve writability at the detriment to readabi

**Comment by JackieXu** [comment]
I also prefer `__log__` over `log`. It looks a bit out of place, but that further accentuates the difference, giving the reader feedback that it's something to look at.

I spent a bit trying to see if the syntax used by Python's `typing` module would work (e.g. `MyLog: Log[num, indexed[address]]`), but that looks a bit strange.

**Comment by DavidKnott** [comment]
@JackieXu `MyLog: Log[num, indexed[address]]` I like this syntax, the issue is that it doesn't allow for the event inputs to be named which is important of readability.

**Comment by DavidKnott** [comment]
Closing this issue now that the functionality has been added.

**Comment by fubuloubu** [comment]
Nice! That's a major one!
