### ISSUE TITLE
max size of `bytes` doesn't appear in ABI output

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#351]
* viper Version: 0.0.1 (although no one has been updating this)
* pyethereum Version: 1.3.7 (patched)
* OS: linux, Ubuntu 16.04 LTS
* Python Version (python --version): 3.6.1
* Environment (output of `pip freeze`):
```bash
alabaster==0.7.10
Babel==2.5.0
bitcoin==1.1.42
bumpversion==0.5.3
certifi==2017.7.27.1
chardet==3.0.4
CommonMark==0.5.4
coverage==4.4.1
docutils==0.14
ethereum==1.3.7
gitdb2==2.0.2
GitPython==2.1.5
idna==2.6
imagesize==0.7.1
Jinja2==2.9.6
MarkupSafe==1.0
pbkdf2==1.3
py==1.4.34
pycryptodome==3.4.6
pyethash==0.1.27
Pygments==2.2.0
pysha3==1.0.2
pytest==3.1.3
pytest-cov==2.5.1
pytest-runner==2.11.1
pytz==2017.2
PyYAML==3.12
recommonmark==0.4.0
repoze.lru==0.6
requests==2.18.4
rlp==0.5.1
scrypt==0.8.0
semantic-version==2.6.0
serpent==1.23
six==1.10.0
smmap2==2.0.3
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
urllib3==1.22
viper==0.0.1
```

### What's your issue about?

I was working with the ABI on a testing application for viper and realized that the syntax `bytes <= N` doesn't represent itself in the ABI (e.g. the type appears as just `bytes`)

For example, check the `approve()` function in `examples/wallet/wallet.v.py` vs `viper -f abi examples/wallet/wallet.v.py`

Not sure if this points to a larger problem, but it makes it difficult to perform ABI-based testing and calling if we don't know what the maximum size is for that argument.

### How can it be fixed?

1. Add to ABI output (ensuring `bytes` has corresponding "max size" parameter)
2. Investigate whether there are errors when handling bytes larger than the dictating size in the compiler.

**Comment by JackieXu** [comment]
Interesting, will have to take a look. I know Solidity has special fixed-size byte arrays called `bytes1`, `bytes2`, ..., `bytes31` and `bytes32`, but there is also the dynamically sized `bytes` type.

It looks like Viper always compiles it to `bytes`.

According to the [`to_abi_dict`](https://github.com/ethereum/viper/blob/master/viper/function_signature.py#L90) method, the [`canonicalize_type`](https://github.com/ethereum/viper/blob/master/viper/types.py#L128) method is used to determine the type of an input/output, and that method *always* returns `bytes` for the `ByteArrayType`, even though an instance of that class has a `maxlen` attribute.

If the ABI stays consistent with the Solidity one, then you could simply check the `maxlen` attribute (if it's less than 32), and set the appropriate number accordingly:

```python
if isinstance(t, ByteArrayType):
    if t.maxlen <= 32:
        return 'bytes%d' % t.maxlen
    else:
        return 'bytes'
```

**Comment by DavidKnott** [comment]
@fubuloubu Great catch!  I already fixed this, I had to add the `maxlen` for the logging feature I'm working on.

**Comment by fubuloubu** [comment]
@DavidKnott ref that PR and I'll close this then

**Comment by jacqueswww** [comment]
@DavidKnott @fubuloubu I think this can be closed now, the logging PR was: https://github.com/ethereum/viper/issues/410

**Comment by fubuloubu** [comment]
@jacqueswww Wrong issue #?

**Comment by jacqueswww** [comment]
@fubuloubu completely wrong number yes, I meant PR https://github.com/ethereum/viper/pull/359

**Comment by fubuloubu** [comment]
Nice. Closing
