### ISSUE TITLE
Feature is_contract method

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/viper#365]
### What's your issue about?

There's currently no way to check if an address is a contract.

### How can it be fixed?

Create an `is_contract` method for addresses.

Test via:
contract_1 = 
```python
def foo():
    pass
```
contract_2 = 
```python
def foo(arg1: address) -> bool:
    return arg1.is_contract
```
```python
c1 = compile(...)
c2 = compile(...)
assert c1.foo(c2.address) == True
assert c1.foo(t.a1) == False
```

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/17552858/30967526-cee84962-a419-11e7-9582-b413beffd1b0.png)

**Comment by fubuloubu** [comment]
Nice, syntax is clear. Do address objects on on the chain contain additional information that allows us to determine it's status, or will parsing the address (e.g. address has code) be required?

**Comment by DavidKnott** [comment]
Parsing the address is required, behind the scenes `is_contract` will use the `EXTCODESIZE` opcode which checks that size of code at a given address.

**Comment by DavidKnott** [comment]
@fubuloubu What do you think about `is_contract?` or just `contract?`

**Comment by fubuloubu** [comment]
`is_contract` it's a boolean return type. `addr.contract` to me should return the code contents (or maybe that is how to convert an address to a contract? Is that even a necessary use case?)

**Comment by jacqueswww** [comment]
I vote for is_contract, as reads easier for booleans ;)

**Comment by DavidKnott** [comment]
This functionality has been added.
