### ISSUE TITLE
FEATURE: Oracles

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/viper#374]
Random musing I was having:
Is it possible to write an HTTP GET Method implementation in EVM where the resulting data is some JSON object queried by a base URL (with  standardized query terms) with some quantified and guaranteed key path (e.g. if the requested key path doesn't exist in the queried data, `throw`)

This is probably more of a general EVM question, I was thinking about it from a language point of view, like it be very useful to create a set of simple and common oracle interactions as a Viper language feature. @DavidKnott what do you think?

**Comment by DavidKnott** [comment]
@fubuloubu I like the idea, but I as of now the evm doesn't support http.  Right now I think this functionality could be a web3 and Viper library add-on but I'm reluctant to add oracle support directly to viper because it seems a bit too specialized.

**Comment by pdaian** [comment]
@fubuloubu see the Town Crier, oraclize.it, smartcontract.com, ChainLink (link.smartcontract.com), and TLSNotary projects among many others :).

These features all need to be added at the EVM level, and should have relatively "Viper native" functionality already (they're all based on standard call functionality).

The only Viper-specific functionality that I think would help would be better external call functionality :).

**Comment by fubuloubu** [comment]
@pdaian Thanks for the overview. I am not too familiar with the whole ecosystem yet, I'd love to see standardization into the EVM for this sort of service, even though I understand it is tricky. My thought was that basically Code (inner functionality) and Events (output to real world) existed, but Oracle (input from real world) is not a standardized thing. I'm sure there are a lot of discussions in that regard, but I think Viper needs this functionality as standardized at some point to be truly successful.

**Comment by daniel-jozsef** [comment]
I really don't see how the EVM should or could be able to access off-chain resources. Contract code is run on all validators. That would mean hundreds or thousands of requests to the same URL. Also, this would make contract executions non-replicable.

Say, a state change is conditional of an off-chain URL. A few blocks ago it succeeded. Now it would fail. How do you validate that block? It's literally impossible, you need to take the miner's (validator's) word for it that the URL returned a valid result at the time. Maybe they are lying, maybe not.

I'm sure there are some things that are best implemented in layer 2, and oracles, in my opinion, are one of them.

**Comment by fubuloubu** [comment]
Yup, I meant to close it. Good point.
