### ISSUE TITLE
Add line numbers to basetype exceptions

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#415]
### What's your issue about?

`base_type_conversion` and `makesetter` throw relevant Structure & Type Exceptions without line numbers.

### How can it be fixed?

Just do it @jacqueswww :package: 

#### Cute Animal Picture

![](http://www.50-best.com/images/cute_animal_pictures/pdog_with_glasses.jpg)

**Comment by fubuloubu** [comment]
Great catch!

**Comment by jacqueswww** [comment]
Fixed ;)
