### ISSUE TITLE
Minimal contract not compiling to ABI/JSON

### ISSUE THREAD

**Issue by chgue** [ethereum/viper#423]
### What's your issue about?
A minimal contract consisting of only an `__init__():` function compiles with the `bytecode` and `ir` flags but not with the `abi` and `json` flags, which throw:
```
".../viper/compiler.py", line 20, in gas_estimate
IndexError: list index out of range
```
### How can it be fixed?
Fixing the `gas_estimate` function so that it handles this special case correctly.

#### Cute Animal Picture

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Amphiprion_ocellaris_%28Clown_anemonefish%29_in_Heteractis_magnifica_%28Sea_anemone%29.jpg/450px-Amphiprion_ocellaris_%28Clown_anemonefish%29_in_Heteractis_magnifica_%28Sea_anemone%29.jpg)

**Comment by jacqueswww** [comment]
On it. :)

**Comment by chgue** [comment]
Thanks for the fix @jacqueswww! :+1: 
Closing.

**Comment by jacqueswww** [comment]
Anytime! :)

**Comment by JhonnyJason** [comment]
@chgue 
What about these cute animal pictures, where do you get them from? is there a code for it? XD

Facing the same problem for this case:

```vyper
# @version ^0.2.8

INITIAL_MINT_CEILING: constant(uint256) = 100000000000000000000000 #100k
INITIAL_MINTABLE_PRO_ETH: constant(uint256) = 666

############################################################
struct Parameters:
    mintableProETH: Bytes[2]
    mintCeiling: Bytes[15]

############################################################
params: Parameters

############################################################
@external
def __init__():
    self.params.mintableProETH = slice(convert(INITIAL_MINTABLE_PRO_ETH, bytes32), 30, 2)
    self.params.mintCeiling = slice(convert(INITIAL_MINT_CEILING, bytes32), 17, 15)
```
Might be related? Open new Issue?

**Comment by iamdefinitelyahuman** [comment]
Looks different..  yes, please open a new issue :)
