### ISSUE TITLE
If in range support

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#428]
### What's your issue about?

Allow Ast.In syntax, such as:

```python
def in_test() -> bool:
    if x in [1, 2, 3, 4]:
        return True
    return False
```

Part of #390  :)

### How can it be fixed?

Just do it :heavy_check_mark: 

#### Cute Animal Picture

![](https://i.ytimg.com/vi/Ayp2YeIfbq4/maxresdefault.jpg)

**Comment by jacqueswww** [comment]
I'm on it! :smile:

**Comment by jacqueswww** [comment]
@fubuloubu Definitely, however I don't think I have actually been able to create list without fixed length (I tried the other day it's super difficult). Do you know how - so I can put the test case ?

**Comment by fubuloubu** [comment]
Oh, yeah I mean we were talking about adding a simple `push()`/`pop()` type list a while back. Would be very useful for creating stacks and queues, as such uses can be accomplished with constant gas estimation. Not sure if it was still on the table, but we were talking about it.

**Comment by jacqueswww** [comment]
Interesting! Yeah that would mean we'd need an in memory counter for the lists' size extra ;) can be done - ping me when the discussion is brought up again :)

**Comment by jacqueswww** [comment]
This has been merged :smiley_cat:
