### ISSUE TITLE
Inconsistency of the value range of type `num`

### ISSUE THREAD

**Issue by daejunpark** [ethereum/viper#453]
* viper Version: 0.0.2
* OS: linux
* Python Version (python --version): 3.6.1

### What's your issue about?

The following three do *not* agree on the value range of type`num`.

1. The [doc](https://viper.readthedocs.io/en/latest/types.html) says: `num` = [-2\*\*127+1, 2\*\*127-2]
> ``num``:  equivalent to``int128``, a signed integer strictly between -2\*\*127 and 2\*\*127-1.

2. `clamp` accepts [-2\*\*127, 2\*\*127-1]

```
def foo():
    one = 1
    x =  170141183460469231731687303715884105726 + one #  2**127 - 1
    z = -170141183460469231731687303715884105727 - one # -2**127
```

3. Viper compiler accepts [-2\*\*127+1, 2\*\*127-1]

For the following program:
```
def foo():
    x =  170141183460469231731687303715884105727 #  2**127 - 1
    y = -170141183460469231731687303715884105727 # -2**127 + 1
    z = -170141183460469231731687303715884105728 # -2**127
```
Viper compiler complained:
```
line 4: Number out of range: 170141183460469231731687303715884105728
    z = -170141183460469231731687303715884105728 # -2**127
---------^
```
### How can it be fixed?

Identify the correct behavior out of the three, and fix the other two.

#### Cute Animal Picture

```
o                  o             o                  o
  o ___/|__          o            o   o              o
o _/       \  /| o              o     ___/|__      o
 /  @ \\    \/ |    o            o  _/       \  /|   o  ___/|__
 \_   //    /\ |  o  ___/|__       /  @ \\    \/ | o  _/       \  /|
   \_______/  \| o _/       \  /|  \_   //    /\ |  o/  @ \\    \/ |
                  /  @ \\    \/ |    \_______/  \|   \_   //    /\ |
                  \_   //    /\ |                      \_______/  \|
                    \_______/  \| 
```

**Comment by fubuloubu** [comment]
Number 2. is correct, 1. and 3. are wrong

Do we not test the extreme limits of num in those tests?
