### ISSUE TITLE
Duplicate ceil32 functions.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#488]
### What's your issue about?
I just realised realised we have duplicate ceil32 implementations. 

![image](https://user-images.githubusercontent.com/6917456/33130582-838262ba-cf9c-11e7-846f-a23c335ef5c1.png)

### How can it be fixed?
Pick one, and replace any references to the deleted one.

```return x if x % 32 == 0 else x + 32 - (x % 32)``` is the one pyethereum also uses, so I am leaning towards using this one, also having it placed in the `utils.py` file makes the most sense.

#### Cute Animal Picture

![](http://www.furrytalk.com/wp-content/uploads/2012/01/22.jpg)

**Comment by fubuloubu** [comment]
;+1: for de-duplication
