### ISSUE TITLE
Add function name to visibility exception.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#489]
### What's your issue about?
Currently the visibility on function exception displays no information, making it difficult to know where to add the visibility decorator.

```python
viper.exceptions.StructureException: Function visibility must be declared (@public or @internal)
```

### How can it be fixed?

Add the function name, bonus if you could add the line number :)

#### Cute Animal Picture

![](https://i.pinimg.com/736x/a9/b2/c3/a9b2c37e53ec0d3eb310fc2abd30a045--cute-animal-photos-funny-animal-pictures.jpg)

**Comment by fubuloubu** [comment]
:+1:
