### ISSUE TITLE
% doesn't clamp_nonzero when divisor is decimal

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#493]
### What's your issue about?
viper code:
`p = x % 0.0` is compile into `[smod, [mul, [mload, 320 <x>], 10000000000], 0]`
without checking whether the divisor is zero.

### How can it be fixed?
in expr.py:
```
def arithmetic(self):
    ...
    elif isinstance(self.expr.op, ast.Mod):
        ...
        elif ltyp == 'num' and rtyp == 'decimal':
            o = LLLnode.from_list(['smod', ['mul', left, DECIMAL_DIVISOR], ['clamp_nonzero', right]],
                                  typ=BaseType('decimal', new_unit), pos=getpos(self.expr))
```

#### Cute Animal Picture
![holgs2x](https://user-images.githubusercontent.com/5641590/33158197-831f8ca4-cfcd-11e7-8e06-e9c57c302989.jpg)

**Comment by fubuloubu** [comment]
Good catch, that is definitely a problem!
