### ISSUE TITLE
vipercoin.v.py doesn't fullfill ERC20 standard

### ISSUE THREAD

**Issue by adhikasp** [ethereum/viper#505]
### What's your issue about?

The `vipercoin.v.py` contract example returning `False` instead of `throw/assert` in function:

- `transfer()`
- `transferFrom()`

As defined in [ERC20 standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md#transfer), those 2 function should throw in case of insufficient fund.

### How can it be fixed?

Change the logic to using assertion or use viper built-in `num256_sub`/`num256_add` that will automatically throw if substraction result is negative.

#### Cute Animal Picture

![picity pic](https://i.pinimg.com/736x/55/fd/40/55fd40c913214f6f38922cbfd366c71a--cute-animal-illustration-animal-illustrations.jpg)

**Comment by DavidKnott** [comment]
@adhikasp Thanks for catching this!  I'm on it.

**Comment by jacqueswww** [comment]
Cool thanks @adhikasp. @DavidKnott what is interesting is the whole point of having a bool here then, if it never returns False :tongue:

**Comment by DavidKnott** [comment]
@jacqueswww I agree, closing.
