### ISSUE TITLE
The scope of index variable is different in "for ... in ... range()" and "for ... in ... list()"

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#509]
### What's your issue about?
There are two programs:
```
@public
def foo(x:num): 
    p = 0 
    for i in range(3): 
        p += i
    for i in range(4): 
        p += i
```
```
@public
def foo(x:num): 
    p = 0 
    for i in range(3): 
        p += i
    for i in [1, 2, 3, 4]: 
        p += i
```
The compiler accepts the first program but rejects the second program.

### How can it be fixed?

I'm not sure whether this behavior is intended or not. In python, it accepts both program. In my opinion, at least it should  both accepts OR both rejects the program OR document this behavior properly.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33235384-42ac55c6-d1fd-11e7-9e8f-ed0385a42e60.png)

**Comment by fubuloubu** [comment]
@jacqueswww you implemented the `i in list` feature right? Is `i` implemented as a variable in the calling scope? It should only exist in the `for` loop scope (i.e. destroyed after usage)

**Comment by jacqueswww** [comment]
@DavidKnott can be close now ;)
