### ISSUE TITLE
[Question] Attack Vector described in Vipercoin's `approve` annotation

### ISSUE THREAD

**Issue by sdtsui** [ethereum/viper#510]
In [L89 of `vipercoin.v.py`](https://github.com/ethereum/viper/blob/master/examples/tokens/vipercoin.v.py#L89), the `approve` method has an annotation that begins like this

>To prevent attack vectors like the one described here and discussed here,

I don't see any description of the attack vectors described, perhaps there should be an external link here?  Point me in the right direction and I can make the PR for it. :)

Thanks!

**Comment by DavidKnott** [comment]
[This](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md) is the page where the `note` is from.
Please have `described here` link to (https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit)
and `discussed here` link to (https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729)
Thanks a lot!

**Comment by sdtsui** [comment]
@DavidKnott PR made! /\

**Comment by DavidKnott** [comment]
@sdtsui Thanks a lot for the contribution!
