### ISSUE TITLE
Compiler doesn't check the number of event arguments consistent with event declarations.

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#519]
### What's your issue about?
```
Transfer: __log__({_from: indexed(num), _to: indexed(num), _value: num})

@public
def foo():
    log.Transfer(1, 2, 3, 4, 5, 6, 7, 8, 9 ,10)
```
The compiler compiles the above program (but should reject as the number of arguments doesn't match the number of parameters in the declaration).

### How can it be fixed?

In stmt.py, add proper check in the `def call(self)` method.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33288852-42132f40-d383-11e7-86b5-309c8ecf0ba3.png)

**Comment by fubuloubu** [comment]
Dang, that's a great catch!
