### ISSUE TITLE
Event logging doesn't handle the situation when the type of a variable ListType.

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#521]
### What's your issue about?
Two programs:
```
Bar: __log__({_value: num[2]})

@public
def foo():
    log.Bar([1, 2])
```
```
Bar: __log__({_value: num[2]})

@public
def foo():
    a = [1, 2]
    log.Bar(a)
```
The first program compiles but the second program throws python exception "AttributeError: 'Name' object has no attribute 'elts'" because `pack_args_by_32` only handles list literals.

### How can it be fixed?

In `pack_args_by_32`, add logic to handle variable of ListType.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33298951-e299f978-d3ae-11e7-84ce-d7e5ffc59312.png)

**Comment by jacqueswww** [comment]
On it. :+1: thanks @yzhang90 :)
