### ISSUE TITLE
Event parameter doesn't support unit type

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#525]
### What's your issue about?

```
MyLog: __log__({arg1: indexed(num(wei))})
```
is a valid event declaration, but
```
 MyLog: __log__({arg1: num(wei)})
```
is not. It seems that the compiler confuses indexed topic with unit type.

### How can it be fixed?

In `event_signature.py`, add logic to differentiate topic declaration and unit type.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33356963-2e5cde12-d485-11e7-9ebf-503193a56523.png)

**Comment by jacqueswww** [comment]
On it, thanks for the bug report :)
