### ISSUE TITLE
Compiler doesn't check the actual return type (when it is a ListType) 

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#531]
### What's your issue about?
```
@public
def foo()->bool[2]:
    a: decimal[2]
    a[0] = 1
    return a
```
```
@public
def foo()->bool[2]:
    a: bool[1000]
    a[0] = 1
    return a
```
Viper accepts the above programs which don't seem to be correct. The compiler will neither check the list subtype nor the number of elements in the list.

### How can it be fixed?

add checking in `def parse_return`

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33407265-2b7c78b8-d536-11e7-9ad8-409ab77a1dcd.png)

**Comment by jacqueswww** [comment]
Thanks! I will tackle this one next :smile:
