### ISSUE TITLE
Log topic and data allow byte array longer than 32 bytes.

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#546]
### What's your issue about?
When packing data/topic for log, if the the actual argument is a byte array variable, there is no check for the actual length of the variable.
e.g.,
```
MyLog: __log__({arg1: indexed(bytes<=2000)})

@public
def foo():
    a: bytes<=100
    log.MyLog(a)
```
This program should be rejected by is not.

### How can it be fixed?

Add check in event_sig, pack_arg_by_32 and pack_logging_topic.

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/5641590/33631206-753fab08-d9cf-11e7-89b4-f2d71f844453.png)

**Comment by fubuloubu** [comment]
Strictly speaking, `bytes<=100` maintains the invariant of the space provided by the log, e.g `bytes<=2000`

I could see a scenario where you might want to bundle things together inside a larger allocation of bytes (you might not know the shape of the bundle beforehand). Not sure if this affects verification, in my mind all that you're verifying is the size in bytes is not exceeded. My 2 wei

**Comment by yzhang90** [comment]
@fubuloubu I was told by @DavidKnott that 32 byte topics is an evm constraint while 32 byte data is a Viper constraint. The length of a topic should not exceed 32 bytes (This is enforced on string literals, seehttps://github.com/ethereum/viper/blob/b0cec59d24051e3bb3577475211c277e78c68a23/viper/parser/parser.py#L665)
