### ISSUE TITLE
Duplication semantics between "suicide" and "selfdestruct"

### ISSUE THREAD

**Issue by yzhang90** [ethereum/viper#548]
### What's your issue about?

Viper has support for `suicide` and  `selfdestruct`.  Their semantics are the same. To avoid confusion, it's better to keep only one statement.
 
### How can it be fixed?

Since `selfdestruct` is more self-explained than `suicide`, just keep `selfdestruct` and remove `suicide`.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33680637-e21f2c68-da87-11e7-8fef-8ca2b2498c78.png)

**Comment by fubuloubu** [comment]
:+1:

**Comment by fubuloubu** [comment]
just checked, no usage in any examples or anything

**Comment by fubuloubu** [comment]
@DavidKnott `SUICIDE` opcode has a different number at the end inside `viper/opcodes.py` Whats up with that?

**Comment by jacqueswww** [comment]
+1 let's remove `suicide` key word.

**Comment by DavidKnott** [comment]
@fubuloubu Not sure, `SUCIDE` might've had a different cost before.  Won't look into it too much given that we're taking it out.

**Comment by fubuloubu** [comment]
Lol, well if they do the same thing but have a different cost can we use the one that has the least cost behind the scenes?

**Comment by DavidKnott** [comment]
@yzhang90 Closing this now that we've removed `sucide`
