### ISSUE TITLE
Fix: Support for logging lists from storage

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#551]
### What's your issue about?
Currently code that retrieves a list from storage and echoes it out to a log statement throws a compile error.
```python
Bar: __log__({_value: num[4]})
x: num[4]

@public
def foo():
    log.Bar(self.x)
```

### How can it be fixed?

Check `pack_args_by_32` function and add support for it :smile: 

Thanks goes out to @yzhang90 for finding it.

#### Cute Animal Picture
![](https://i.pinimg.com/originals/35/83/1e/35831ea13d7675f139eccb52a6d655d2.jpg)

**Comment by yzhang90** [comment]
Please also take a look at byte array variable, the storage case is not handled there as well.

**Comment by jacqueswww** [comment]
On it.
